
export const SHAREDO_EVENTS = ['sharedo.core.case.phase-changed', 'sharedo.core.case.components.related-documents.data-changed', 'sharedo.core.case.document-delivery-task-created', 'sharedo.core.case.keyfacts.updated', 'Sharedo.Core.Case.Participants.Updated', 'sharedo.core.case.components.taskList.data-changed', 'sharedo.core.case.sharedo-updated', 'sharedo.core.case.forms.phase.phase-changed', 'Sharedo.Core.Legal.Proceedings.Updated', 'sharedo.legal.updated', 'Sharedo.Core.Legal.Finance.Refresh', 'Sharedo.Core.Case.Fees.Version.Updated', 'sharedo.core.case.components.comments.content-updating', 'sharedo.core.case.components.comments.content-update-complete', 'Sharedo.Core.Legal.Participants.Updated', 'sharedo.core.case.participants-reordered', 'Sharedo.Core.Legal.Widgets.TaskList.data-changed', 'Sharedo.Core.Legal.Incidents.Updated', 'Sharedo.Core.Case.Widgets.Scorecards.Updated', 'dynamic-radar-opening', 'sharedo.updated', 'sharedo.core.case.components.comments.comments-changed', 'sharedo.core.case.components.portfolioList.data-changed', 'core.case.plan-view.undo', 'Sharedo.Core.Case.DataQuality.CallToActionDone', 'sharedo.core.case.action-plan.changed', 'Sharedo.Core.Case.ActionPlanActions.TaskCreatedFromCallToAction', 'user-profile-check-external-accounts', 'sharedo.core.case.components.user-availability-changed', 'oauth-link-complete', 'sharedo.shownotifications', 'sharedo.bookmarks.updated', 'time-recording.active-stopwatch.data-changed', 'sharedo.core.case.components.comments.data-changed', 'sharedo.core.case.components.comments.config-changed', 'sharedo.core.case.components.comments.filter-changed', 'sharedo.ui.framework.lync.statusChanged', 'sharedo.core.case.components.user-profile-image-changed', 'core.sharedo.affected', 'sharedo.core.case.sharedo-created', 'sharedo.core.case.refresh-ribbon', 'sharedo.core.case.sharedo-toolbar-action-completed', 'sharedo.core.case.action-plan.updated', 'sharedo.core.case.action-plan.changing', 'ko.bindingHandlers.groupPanelBehaviour.start', 'ko.bindingHandlers.groupPanelBehaviour.complete', 'Sharedo.Core.Case.Components.PortfolioBreakdownByTypeChart.chartBreakdownByPhase.select', 'admin-list-views-updated'].sort();

export const REFRESH_WATCHER_FORMIO = {
    "_id": "650cc8d5e4f0d54921a6c8ec", "title": "Designer", "name": "designer", "path": "designer", "type": "form", "display": "form", "tags": [], "access": [{ "type": "create_own", "roles": [] }, { "type": "create_all", "roles": [] }, { "type": "read_own", "roles": [] },
    { "type": "read_all", "roles": ["650cc833523213eb8b726e9c", "650cc833523213eb8b726ea0", "650cc833523213eb8b726ea4"] },
    { "type": "update_own", "roles": [] }, { "type": "update_all", "roles": [] }, { "type": "delete_own", "roles": [] },

    { "type": "delete_all", "roles": [] }, { "type": "team_read", "roles": [] }, { "type": "team_write", "roles": [] },
    { "type": "team_admin", "roles": [] }], "submissionAccess": [{ "type": "create_own", "roles": [] }, { "type": "create_all", "roles": [] },
    { "type": "read_own", "roles": [] }, { "type": "read_all", "roles": [] }, { "type": "update_own", "roles": [] }, { "type": "update_all", "roles": [] },
    { "type": "delete_own", "roles": [] }, { "type": "delete_all", "roles": [] }, { "type": "team_read", "roles": [] }, { "type": "team_write", "roles": [] }, { "type": "team_admin", "roles": [] }], "owner": "650cc76ee4f0d54921a6b4df", "components": [{ "label": "Configuration", "modalEdit": true, "key": "configuration", "type": "well", "input": false, "tableView": false, "components": [{ "label": "Widgets To Refresh", "reorder": false, "addAnother": "Add", "addAnotherPosition": "bottom", "layoutFixed": false, "enableRowGroups": false,
     "initEmpty": false, "tableView": false, "defaultValue": [{ "typeName": "", "methodToExecute": "" }], "key": "widgets", "type": "datagrid", "input": true, "components": [{ "label": "Type Name", "placeholder": "Sharedo.Core.Case.Menus.Widgets.WorkItemRibbon", "applyMaskOn": "change", "columnWeight": 0, "hideColumnByDefault": false, "disableSortingAndFiltering": false, "tableView": true, "key": "typeName", "type": "textfield", "input": true }, { "label": "Method to Execute", "placeholder": "loadAndBind", "applyMaskOn": "change", "columnWeight": 0, "hideColumnByDefault": false, "disableSortingAndFiltering": false, "tableView": true, "key": "methodToExecute", "type": "textfield", "input": true }] }, { "label": "Use Interval ( refresh every x seconds )", "tableView": false, "key": "useIntervalRefreshEveryXSeconds", "type": "checkbox", "input": true, "defaultValue": false }, 
     { "label": "Interval (seconds)", "applyMaskOn": "change", "mask": false, "tableView": false, "delimiter": false, "requireDecimal": false, "inputFormat": "plain", "truncateMultipleSpaces": false, "key": "intervalSeconds", "conditional": { "show": true, "conjunction": "all", "conditions": [{ "component": "useIntervalRefreshEveryXSeconds", "operator": "isEqual", "value": true }] }, "type": "number", "input": true }, { "label": "Refresh on events", "tableView": false, "key": "refreshOnEvents", "type": "checkbox", "input": true, "defaultValue": false }, { "label": "Events To Listen To", "reorder": false, "addAnotherPosition": "bottom", "layoutFixed": false, "enableRowGroups": false, "initEmpty": false, "tableView": true, "defaultValue": [{ "eventName": "" }], "key": "eventsToListenTo", "conditional": { "show": true, "conjunction": "all", "conditions": [{ "component": "refreshOnEvents", "operator": "isEqual", "value": true }] }, "type": "datagrid", "columnWeight": 0, "hideColumnByDefault": false, "disableSortingAndFiltering": false, 
     "input": true, "components": [{ "label": "Event Name", "widget": "html5", "tableView": true, "dataSrc": "custom", "data": { "custom": "return dataContext.eventsOptions" }, 
    "dataType": "auto", "template": "<span>{{ item }}</span>", "key": "eventName", "type": "select", "input": true }] }] }, { "label": "Submit", "showValidations": false, "disableOnInvalid": true, "hidden": true, "tableView": false, "key": "submit", "type": "button", "input": true, "saveOnEnter": false }], "settings": {}, "properties": {}, "project": "650cc833523213eb8b726e95", "controller": "", "revisions": "", "submissionRevisions": "", "_vid": 0, "created": "2023-09-21T22:51:01.111Z", "modified": "2023-09-22T03:16:37.127Z", "machineName": "rpoeptekzqtgopm:designer", "plan": "trial"
}